### ISSUE TITLE
Error on requestArticleInfo function

### ISSUE THREAD

**Issue by yeorinhieut** [aitestai/node-dcinside#1]
{ result: 'false', err_msg: '잘못된 접근입니다.' }

`const { DcinsideApi } = require('node-dcinside');

const client = new DcinsideApi({
    username: 'ㅇㅇ',
    password: 1234
});

(async function () {
    const res = await client.requestArticleInfo('baseball_new11', 5) /** response t_vch1가 I면 아이폰 공앱, S면 운영자, A면 안드로이드 공앱, W면 웹, V면 모바일 웹 */
    console.log(res);
})()`

위와 같은 코드로 ArticleInfo 요청시 { result: 'false', err_msg: '잘못된 접근입니다.' }
에러가 발생합니다.

**Comment by aitestai** [comment]
해당 api는 취약점이 발생하여 디시 측에서 패치했습니다

**Comment by yeorinhieut** [comment]
감사합니다
