### ISSUE TITLE
auth가 있는 프록시 지원

### ISSUE THREAD

**Issue by yeorinhieut** [aitestai/node-dcinside#4]
auth를 사용하는 프록시를 사용할 때,

`작업 중 오류가 발생했습니다: Error: 갤러리를 찾을 수 없습니다: 
    at DcinsideApi.checkVaildGall (node_modules/node-dcinside/dist/api/api.js:966:15)`

문제가 발생합니다.

사용한 코드:
```javascript
const proxyConfig = {
  protocol: 'http',
  host: '',
  port: ,
  auth: {
    username: '',
    password: ''
  }
};

// DcinsideApi 인스턴스 생성
const client = new DcinsideApi({
  username: 'ㅇㅇ',
  password: 1234,
  captcha: true,
  proxy: proxyConfig
}); 
```

**Comment by aitestai** [comment]
안녕하세요! 너무 귀찮아서 혼자만 기능 추가해 쓰면서 이 프로젝트는 업데이트를 안하고 있거든요!

`npm i https-proxy-agent` 입력 후
```javascript
const { HttpsProxyAgent } = require('https-proxy-agent')
let Proxy = new SocksProxyAgent('http://username:password@host:port');
/* 상수 */

// 95 line
this.axios = axios.create({
      httpAgent: Proxy,
      httpsAgent: Proxy
});
```

node_modules/node-dcinside/src/api.js로 직접 가셔서 위와 같이 수정하시면 될거에요!

**Comment by aitestai** [comment]
안녕하세요! 너무 귀찮아서 혼자만 기능 추가해 쓰면서 이 프로젝트는 업데이트를 안하고 있거든요!

`npm i https-proxy-agent` 입력 후
```javascript
const { HttpsProxyAgent } = require('https-proxy-agent')
let Proxy = new HttpsProxyAgent('http://username:password@host:port');
/* 상수 */

// 95 line
this.axios = axios.create({
      httpAgent: Proxy,
      httpsAgent: Proxy
});
```

node_modules/node-dcinside/src/api.js로 직접 가셔서 위와 같이 수정하시면 될거에요!

**Comment by yeorinhieut** [comment]
감사합니당!! 나중에 기여할 일 있으면 기여하겠습니다!

**Comment by yeorinhieut** [comment]
++ 혹시 후록시 사용시 papago ocr이 잘 작동하지 않는것도 비슷한 이슈인가여

**Comment by aitestai** [comment]
디시인사이드의 캡챠 시스템은 같은 아이피로 캡챠 세션과 캡챠 이미지를 요청해야하는데

아마도 Resi 프록시를 사용중이시라면 아이피가 요청마다 바뀌니 디시 서버는 refresh 캡챠 이미지를 리턴하죠

정상적으로 캡챠를 풀고싶다면 사용하시는 Resi 프록시의 session 기능을 사용하면 될겁니다.

**Comment by yeorinhieut** [comment]
오 감사합니당 좋은 모듈 감사드립니다.
